[package]
name = "ruvex_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ruvex_config = {path="../ruvex_config"}
thiserror = "1.0.40"
anyhow = "1.0.8"
regex="1"
clap = { version = "4.2.7", features = ["derive"] }
